CREATE TABLESPACE XKJTABLESPACE DATAFILE 'E:/OracleDB/tablespace/XKJ_DATA_01.DBF'
SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M;
CREATE TEMPORARY TABLESPACE XKJTEMPTABLESPACE TEMPFILE 'E:/OracleDB/tablespace/XKJ_TEMP_DATA_01.DBF'
SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M;
CREATE USER XKJ IDENTIFIED BY "123456" DEFAULT TABLESPACE XKJTABLESPACE TEMPORARY TABLESPACE XKJTEMPTABLESPACE;
GRANT DBA TO XKJ;